spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://220.81.42.179:3306/lodgment
    username: jeong
    password: root
  mail:
    host: smtp.naver.com
    port: 587
    username: ukidd12
    password: lss9750189!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  redis:
    host: 220.81.42.179
    port: 6379
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

secret_settings:
  address: ukidd12@naver.com